// Copyright (c) 2026 StarTechnology. All rights reserved.

#pragma once

#include "Runtime/Launch/Resources/Version.h"

// ────────────────────────────────────────────────────────
// Engine version comparison macros
// ────────────────────────────────────────────────────────

#if (ENGINE_MAJOR_VERSION > 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 4)
#define WN_UE5_4_PLUS 1
#else
#define WN_UE5_4_PLUS 0
#endif

#if (ENGINE_MAJOR_VERSION > 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 5)
#define WN_UE5_5_PLUS 1
#else
#define WN_UE5_5_PLUS 0
#endif

#if (ENGINE_MAJOR_VERSION > 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 6)
#define WN_UE5_6_PLUS 1
#else
#define WN_UE5_6_PLUS 0
#endif

#if (ENGINE_MAJOR_VERSION > 5) || (ENGINE_MAJOR_VERSION == 5 && ENGINE_MINOR_VERSION >= 8)
#define WN_UE5_8_PLUS 1
#else
#define WN_UE5_8_PLUS 0
#endif

// ────────────────────────────────────────────────────────
// FAnsiString availability (added in UE 5.4)
//   - UE5.4+: FAnsiString exists, forward-declared in
//             Containers/ContainersFwd.h with the full
//             definition generated by Containers/AnsiString.h.
//   - UE5.1-5.3: no FAnsiString at all.
// Call sites that need to instantiate TArray<FAnsiString> use
// this macro to choose between the native type (with an explicit
// include of the full definition) and an FString fallback.
// ────────────────────────────────────────────────────────
#if WN_UE5_4_PLUS
	#define WN_ENGINE_HAS_FANSISTRING 1
#else
	#define WN_ENGINE_HAS_FANSISTRING 0
#endif

// ────────────────────────────────────────────────────────
// SViewport compatibility (UE5.3 requires explicit include)
// ────────────────────────────────────────────────────────
// UE5.3: SViewport is forward-declared in GameViewportClient.h and
//        not implicitly included by other headers. Including it
//        explicitly fixes incomplete-type errors on UE5.3 and is
//        harmless on UE5.4+.
#if WN_UE5_4_PLUS == 0
#include "Widgets/SViewport.h"
#endif

// ────────────────────────────────────────────────────────
// AllowShrinking parameter: bool → EAllowShrinking (UE5.4+)
//   In UE 5.8 the deprecated bool overload is fully removed,
//   so EAllowShrinking::No is the only option.
// ────────────────────────────────────────────────────────
#if WN_UE5_4_PLUS
	#define WN_ALLOW_NO_SHRINKING EAllowShrinking::No
#else
	#define WN_ALLOW_NO_SHRINKING false
#endif

// ────────────────────────────────────────────────────────
// TArray::RemoveAt signature change (UE5.5+)
//     UE5.5+: RemoveAt(Index, Count, EAllowShrinking)
//     UE5.4-: RemoveAt(Index, Count, bool bAllowShrinking)
// ────────────────────────────────────────────────────────
#if WN_UE5_5_PLUS
	#define WN_REMOVE_AT_SHRINK(Array, Index, Count, Allow) \
		(Array).RemoveAt(Index, Count, Allow ? EAllowShrinking::Yes : EAllowShrinking::No)
#else
	#define WN_REMOVE_AT_SHRINK(Array, Index, Count, Allow) \
		(Array).RemoveAt(Index, Count, Allow)
#endif

// ────────────────────────────────────────────────────────
// TArray::SetNumUninitialized second parameter (UE5.4+)
//     UE5.4+: SetNumUninitialized(Size, EAllowShrinking)
//     UE5.3-: SetNumUninitialized(Size, bool bAllowShrinking)
// Note: UE5.4 also provides a deprecated bool overload, but
//       we use the native type to avoid deprecation warnings.
// ────────────────────────────────────────────────────────
#if WN_UE5_4_PLUS
	#define WN_SETNUM_UNINITIALIZED_NO_SHRINK(Array, Size) \
		(Array).SetNumUninitialized(Size, EAllowShrinking::No)
#else
	#define WN_SETNUM_UNINITIALIZED_NO_SHRINK(Array, Size) \
		(Array).SetNumUninitialized(Size, false)
#endif

// ────────────────────────────────────────────────────────
// FCoreDelegates::OnPostEngineInit API change (UE5.8+)
//     UE5.8+: FCoreDelegates::GetOnPostEngineInit() 返回引用
//     UE5.7-: FCoreDelegates::OnPostEngineInit 静态成员变量
// ────────────────────────────────────────────────────────
#if WN_UE5_8_PLUS
	#define WN_ON_POST_ENGINE_INIT FCoreDelegates::GetOnPostEngineInit()
#else
	#define WN_ON_POST_ENGINE_INIT FCoreDelegates::OnPostEngineInit
#endif

// ────────────────────────────────────────────────────────
// FSlateTexture2DRHIRef constructor parameter (UE5.5+)
//   - 5.5+: constructor takes FTextureRHIRef,
//           RHICreateTexture2DFromResource returns FTextureRHIRef
//   - 5.4-: constructor takes FTexture2DRHIRef,
//           RHICreateTexture2DFromResource returns FTexture2DRHIRef
// Use 'const auto' for the WrappedRef variable so the deduced
// type matches the constructor automatically.
// ────────────────────────────────────────────────────────
